In [37]:
# Load libraries
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory
from stop_words import get_stop_words
import pandas as pd
import numpy as np 
import string, re
import random

stemmer = StemmerFactory().create_stemmer()
stopwords_id = get_stop_words("id")

def preprocess(text):
    text = text.lower().split(" ")
    text_clean = " ".join([i for i in text if i not in stopwords_id])
    text_stem = stemmer.stem(text_clean)
    result = ''.join([i for i in text_clean if not i.isdigit()])
    result = re.sub(r'[^\w\s]','',result)
    return result

In [57]:
query = "tolong dong kasih referensi judul tentang text mining menggunakan tf idf"
query = query.partition("tentang")[2].lstrip()
query

'text mining menggunakan tf idf'

In [146]:
from sklearn.feature_extraction.text import TfidfVectorizer
class Engine(object):
    
    def __init__(self, query):
        self.dataset = pd.read_excel("dataset_sample.xlsx")
        self.phrase = [query] + self.dataset["preprocessed_title"].tolist()
        self.vectorizer = TfidfVectorizer()
        
    def get_scores(self):
        transform = vectorizer.fit_transform(self.phrase)
        return (transform[0, :] * transform[1:, :].T).A[0]

In [147]:
test = Engine(query=query)
test.get_scores()

array([0.04373243, 0.12370086, 0.16363027, 0.10630784, 0.03926075,
       0.13334239, 0.10400326, 0.14267936, 0.08713263, 0.04255331])

In [66]:
data = ["apa", "dia"]
data[0:1]

['apa']

In [70]:
[query]

['text mining menggunakan tf idf']

In [130]:
dataset = pd.read_excel("dataset_sample.xlsx")
phrase = [query] + dataset["preprocessed_title"].tolist()
title = dataset["preprocessed_title"].tolist()
phrase

['text mining menggunakan tf idf',
 'pengelompokkan data penyakit berdasarkan usia menggunakan metode fuzzy cmeans',
 'text mining menggunakan metode single linkage manhattan distance similarity pengelompokkan trend topik kerja praktik',
 'text mining menggunakan metode snn evclidean distance mengelompokan email',
 'text mining klasifikasi judul skripsi teknik industri universitas ahmad dahlan berdasarkan bidang minat menggunakan metode naive bayes',
 'pengembangan analisis sentimen sistem indeks kinerja dosen menggunakan metode naive bayes',
 'penerapan text mining pengelompokkan judul kerja praktek menggunakan metode kmeans clustering cosineâ\xa0 similarity',
 'pemanfaatan text mining mengklasifikasi sms spam porno algoritma c',
 'implementasi text mining pengelompokkan judul penelitian dosen menggunakan metode kmedoids cosine similarity',
 'aplikasi web text mining pengelompokkan judul jurnal publikasi metode snn  shared nearest neighbor',
 'analisis sentimen komentar tulisan blog m

In [131]:
vectorizer = TfidfVectorizer()

In [139]:
transform_title = vectorizer.fit_transform(title)
transform_query = vectorizer.fit_transform(phrase)
transform_query.toarray()

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.61959633,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.26240158, 0.        , 0.        , 0.        , 0.28578504,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.28578504,
        0.61959633, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ],
       [0.     

In [137]:
# from sklearn.metrics.pairwise import cosine_similarity
# cosine_similarity(transform_query, transform_title)

In [140]:
(transform_query[0, :] * transform_query[1:, :].T).A[0]

array([0.04373243, 0.12370086, 0.16363027, 0.10630784, 0.03926075,
       0.13334239, 0.10400326, 0.14267936, 0.08713263, 0.04255331])